version: 2
defaults: &github-actions-template
  package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "05:00"
    timezone: "America/New_York"
  versioning-strategy: increase
  open-pull-requests-limit: 15
  pull-request-branch-name:
    separator: "-"
  commit-message:
    prefix: "actions"
    prefix-development: "chore(actions)"
    include: "scope"
  labels:
    - "dependencies"
    - "github-actions"
  groups:
    all-actions:
      patterns:
        - "*"
  reviewers:
    - "team:infrastructure"
  assignees:
    - "senior-dev"
  allow:
    - dependency-type: "production"

updates:
  - <<: *github-actions-template
    target-branch: "xer"
  - <<: *github-actions-template
    target-branch: "main"
